import type { Metadata } from "next";
import NavBar from "../Components/NavBar";
import Footer from "../Components/Footer";
import { ToastContainer } from "react-toastify";
import { StoreProvider } from "@/app/Context/JewelryContext";

export const metadata: Metadata = {
  title: "Zina Jewelry",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <StoreProvider>
        <NavBar />
        <main>{children}</main>
        <ToastContainer position="bottom-right" autoClose={3000} />
        <Footer />
      </StoreProvider>
    </>
  );
}
